name: nlp-finance
channels:
- defaults
- conda-forge
dependencies:
- ipykernel>=4.6.1
- jupyter>=1.0.0
- numpy>=1.13.3
- pandas>=0.23.4
- python==3.6.9
- spacy==2.2.1
- pip:
  - matplotlib==3.1.1
  - scikit-learn==0.21.3
  - pyLDAvis==2.1.2
  - language-check==1.1
  - gensim==3.8.1
  - nltk==3.4.5
  - ipython==7.13.0
  - scipy==1.4.1
  - wordcloud==1.6.0
  - bs4==0.0.1
  - plotly==4.5.4
  - xgboost==1.0.2
  - seaborn==0.10.0
  - lxml==4.5.0
  - keras==2.3.1
  - tensorflow==2.1.0